### ISSUE TITLE
Use cases for liblogfaf

### ISSUE THREAD

**Issue by nrshrivatsan** [facebook/liblogfaf#8]
**Praise** - Using UDP is great.

**Request** - Adding use-cases for liblogfaf on readme.md would be very useful.

**Comment by pallotron** [comment]
Thanks for opening this ticket.
I was wondering, Isn't the README clear enough?

> This is useful for processes that call syslog() as part of their main execution flow and can therefore be easily broken when /dev/log buffer gets full, for example when the process that is expected to read from it (usually system syslog daemon like rsyslog or syslog-ng) stops doing that.
> Please note that liblogfaf should not be used in an environment where reliable log message delivery is required.

This library is useful when you have an application, e.g. some sort of network server, that accepts connections and for every query logs stuff using syslog(). Since /dev/log can get full and block any write to it you might end up with lost of delayed responses from your service.
If serving requests is more important for you than logging them you might want to enseure that your logging doesn't block the execution of your processing flow. In this case liblogfaf could help you.
If you can't afford losing even a single message than it is not for you.
liblogfaf comes handy especially when you don't have direct control of your application source code and therefore you cannot modify it to workaround the before mentioned problem.

Of course, even using liblogfaf, you should have monitoring in place to catch situations when your logging system cannot keep up. however when that happens your application is still keeping up with clienet requests.

hope this helps.
